### ISSUE TITLE
[Tip] Using `clang` and `clangd` to setup LSP for development (for VSCode, Emacs, Neovim, e.g.)

### ISSUE THREAD

**Issue by goranmoomin** [swsnu/osspr2022#17]
For people who don't like the Vim + tags setup, one can setup [`clangd`](https://clangd.llvm.org) as a [LSP server](https://microsoft.github.io/language-server-protocol/) and use the helpful go to definition, find references, and completion capabilities in one's favorite editor (e.g. [VSCode](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd)).

For `clangd` to fully understand the codebase, you really need a [JSON compilation database](https://clang.llvm.org/docs/JSONCompilationDatabase.html)  (`compile_commands.json`). By compiling the kernel with `clang` (so that `clangd` exactly understands all compilation flags) and wrapping the compilation process with [Bear](https://github.com/rizsotto/Bear), you can achieve everything quite easily.

Install the required tools, modify `build-rpi3.sh` to use clang, and clean-compile the kernel initially to generate a fresh compilation database.

```shell session
$ sudo apt-get install clang clangd bear
$ cat <<EOF > build-rpi3.sh
#!/bin/bash

############################################
# OSSPR2022                                #
#                                          #
# Builds your ARM64 kernel.                #
############################################

set -e

# Did you install ccache?
type ccache

# Some cleanups and setups
rm -f arch/arm64/boot/Image
rm -f arch/arm64/boot/dts/broadcom/*.dtb
CROSS_COMPILER='aarch64-linux-gnu-'

# Build .config
make ARCH=arm64 CC='ccache clang' CROSS_COMPILE="$CROSS_COMPILER" tizen_bcmrpi3_defconfig

# Build kernel
make ARCH=arm64 CC='ccache clang' CROSS_COMPILE="$CROSS_COMPILER" -j$(nproc)
EOF
$ make clean
$ rm compile_commands.json && bear ./build-rpi3.sh
```

At this point you can probably use `clangd` without any problems – configuring your editor to use it will now provide completions. (One configuration example would be using VSCode with the [official `clangd` extension](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd).) Once the compilation database is initially created, just keep using `bear ./build-rpi3.sh` for compiling and `bear` will incrementally update the compilation database.

BTW: when using `clang`, confirm that creating the image and booting from `qemu` works and has not caused any regressions – AFAIK our version of Linux supports `clang` compilation, but I take no responsibility on errors that only manifest from using `clang`.

**Comment by hyeongyukim** [comment]
Great! I'm also a big fan of LSP.
But I think we do not have to use clang to compile kernels.
`Clangd` is maintained by llvm/clang devs, but its behavior does not depend on clang. If you deliver the correct `compile_commands.json` to `Clangd`, it will work correctly whether the compiler is clang or GCC. I have never used `Clangd` before, but at least for `ccls` (another implementation of c/c++ lsp server), it works well with GCC. ([FAQ link](https://github.com/MaskRay/ccls/wiki/FAQ))

**Comment by goranmoomin** [comment]
@hyeongyukim I've never used `ccls`, but `clangd` errors out on unknown flags that only `gcc` understands.

**Comment by eomiso** [comment]
@goranmoomin Is Jumping on to definitions also working for your setting? 
I'm using `nvim + coc.nvim + clangd`, and weirdly the code completion works perfectly fine but jumping to definitions and finding references doesn't seem to work.

**Comment by tirr-c** [comment]
For those who use clangd, create a file named `.clangd` at the project root with the following:

```yaml
CompileFlags:
  Add:
  - '--gcc-toolchain=/usr'
  Remove:
  - '-mabi=lp64'
  - '-falign-jumps=1'
  - '-falign-loops=1'
  - '-fconserve-stack'
  - '-fmerge-constants'
  - '-fno-code-hoisting'
  - '-fno-schedule-insns'
  - '-fno-sched-pressure'
  - '-fno-var-tracking-assignments'
  - '-fsched-pressure'
  - '-mhard-float'
  - '-mindirect-branch-register'
  - '-mindirect-branch=thunk-inline'
  - '-mpreferred-stack-boundary=2'
  - '-mpreferred-stack-boundary=3'
  - '-mpreferred-stack-boundary=4'
  - '-mrecord-mcount'
  - '-mindirect-branch=thunk-extern'
  - '-mno-fp-ret-in-387'
  - '-mskip-rax-setup'
  - '--param=allow-store-data-races=0'
  - '-Wa,arch/x86/kernel/macros.s'
  - '-Wa,-'
```

Then, populate `compile_commands.json` with `bear ./build_rpi3.sh` (or `bear -- ./build_rpi3.sh` if you are using newer versions of BEAR).
